---

- name: Disable shared allocation
  uri:
    url: http://localhost:9200/_cluster/settings?format=json
    method: PUT
    body: '{ "persistent": { "cluster.routing.allocation.enable": "primaries" } }'
    status_code: 200
    body_format: json
    return_content: yes
  register: result
- name: Fail the shared allocation
  fail: msg="Shared allocation failed"
  when: result.json.acknowledged != true
