---

# Change the repo name and content for any major upgrade
- name: Check yum repo.d file exists
  stat:
    path: /etc/yum.repos.d/elasticsearch-7.repo
  register: stat_result
- name: Create ES repo.d file if not exists
  when: not stat_result.stat.exists
  copy:
    dest: /etc/yum.repos.d/elasticsearch-7.repo
    owner: root
    group: root
    mode: 0644
    content: |
      [elasticsearch]
      name=Elasticsearch repository for 7.x packages
      baseurl=https://artifacts.elastic.co/packages/7.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
